# By default, Docker names project directory name, names built images {project}_{service}, and names each container {project}_{service}_{index}
version: "3.8"

services:   
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"

    aligner:
        image: cnbeining/gentle:latest
        ports:
            - "8765:8765"