name: Docker Image CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  |
        docker build . --file Dockerfile --tag seanfarhat/karaoke:latest
        docker push seanfarhat/karaoke:latest
